// Copyright 2020 Andrew Quinn. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gofrac

import (
	"errors"
	"math"
	"math/cmplx"
	"runtime"
	"sync"
)

//var debug = log.New(os.Stdout, "DEBUG: ", log.LstdFlags)

// Fraccer maps a point in the complex plane to the result of a fractal calculation
type Fraccer interface {
	// Frac performs iterations of a fractal equation for a complex number
	// given by loc.
	Frac(loc complex128) *Result
	Data() *FracData
	SetMaxIterations(iterations int) error
}

// FracIt applies the fractal calculation given by f to every sample in the
// domain d. The maximum number of iterations to be performed is given by
// iterations.
func FracIt(d DomainReader, f Fraccer, iterations int) (*Results, error) {
	err := f.SetMaxIterations(iterations)
	if err != nil {
		return nil, err
	}

	rows, cols := d.Dimensions()
	if cols < 1 || rows < 1 {
		return nil, errors.New("gofrac: the domain must be sampled at least once along each axis")
	}

	results := NewResults(rows, cols, iterations)
	defer results.Done()

	rowJobs := make(chan int, rows)

	numWorkers := runtime.NumCPU()
	wg := sync.WaitGroup{}
	for worker := 0; worker < numWorkers; worker++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for row := range rowJobs {
				for col := 0; col < cols; col++ {
					loc, err := d.At(col, row)
					if err != nil {
						panic(err)
					}
					r := f.Frac(loc)
					results.SetResult(row, col, r.Z, r.C, r.Iterations)
				}
			}
		}()
	}

	for row := 0; row < rows; row++ {
		rowJobs <- row
	}

	close(rowJobs)
	wg.Wait()

	return &results, nil
}

type FracData struct {
	// Radius is the bailout radius of a fractal calculation.
	Radius float64

	// MaxIterations is the number of iterations at which an iterated input value is considered convergent if it hasn't
	// exceeded Radius.
	MaxIterations int

	// Degree is the degree of the complex polynomial function to be iterated.
	degree float64

	logDegreeInv float64
}

func (f *FracData) Data() *FracData {
	return f
}

func (f *FracData) SetRadius(r float64) {
	f.Radius = r
}

func (f *FracData) SetMaxIterations(n int) error {
	if n < 1 {
		return errors.New("gofrac: the maximum iteration count must be greater than zero")
	}
	f.MaxIterations = n
	return nil
}

func (f *FracData) SetDegree(d float64) {
	f.degree = d
	f.logDegreeInv = 1 / math.Log(d)
}

// Quadratic stores the information needed by a quadratic fractal.
type Quadratic struct {
	FracData
}

func (q Quadratic) q(z complex128, c complex128) *Result {
	count := 0
	for mod := cmplx.Abs(z); mod <= q.Radius; mod, count = cmplx.Abs(z), count+1 {
		z = z*z + c
		if count == q.MaxIterations-1 {
			break
		}
	}
	return &Result{
		Z:          z,
		C:          c,
		Iterations: count,
	}
}

// The Mandelbrot set, which results from iterating the function
// f_c(z) = z^2 + c, for all complex numbers c and z_0 = 0.
type Mandelbrot struct {
	Quadratic
}

func NewQuadratic(radius float64) Quadratic {
	q := Quadratic{
		FracData{
			Radius: radius,
		},
	}
	q.SetDegree(2.0)
	return q
}

// NewMandelbrot constructs a Mandelbrot struct with a given bailout radius.
func NewMandelbrot(radius float64) *Mandelbrot {
	return &Mandelbrot{
		Quadratic: NewQuadratic(radius),
	}
}

func (m Mandelbrot) Frac(loc complex128) *Result {
	return m.q(0, loc)
}

// JuliaQ is the quadratic Julia set, which results from iterating the function
// f_C(z) = z^2 + C for a all complex numbers z and a given complex number C.
type JuliaQ struct {
	Quadratic
	C complex128
}

// NewJuliaQ constructs a new JuliaQ struct with a given bailout radius and a
// complex parameter c corresponding to the C in f_C(z) = z^2 + C.
func NewJuliaQ(radius float64, c complex128) *JuliaQ {
	return &JuliaQ{
		Quadratic: NewQuadratic(radius),
		C: c,
	}
}

func (j JuliaQ) Frac(loc complex128) *Result {
	return j.q(loc, j.C)
}

// JuliaR is a Julia set generated by a rational complex function given by
// f_C(z) = P(z) / Q(z) + C.
type JuliaR struct {
	FracData
	P func(complex128) complex128
	Q func(complex128) complex128
	C complex128
}

func (r JuliaR) Frac(loc complex128) *Result {
	z := loc
	count := 0
	for mod := cmplx.Abs(z); mod <= r.Radius; mod, count = cmplx.Abs(z), count+1 {
		z = r.P(z)/r.Q(z) + r.C
		if count == r.MaxIterations-1 {
			break
		}
	}
	return &Result{
		Z:          z,
		C:          r.C,
		Iterations: count,
	}
}
